### PR TITLE
Added a fuzzer for integration with oss-fuzz.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi Maintainers,

I have worked a bit on setting fuzzing up for sql-parser by way of OSS-Fuzz. Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects, and it would be great to have sql-parser integrated. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

In this PR https://github.com/google/oss-fuzz/pull/5276 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate sql-parser. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

At the moment I stored the fuzzers in the Google OSS-Fuzz repository, but we can move them up here to make maintenance easier.

### CODE REVIEW

**Comment by mrks** [comment]
This sounds great. As I will soon be handing over the ownership of the repo to another Hyrise developer, I suppose it's fine to discuss this with him first before we enter a commitment. Please give us a week for that.

Do you by any chance have a sample report that we can have a look at? Could you please send it to markus.dreseler@hpi.de?

**Comment by DavidKorczynski** [comment]
Sounds good.

As for the reports, I think it's easier to describe them. The reports are composed of:
1) stack traces of the crash run with a sanitizer
2) the input to the fuzzer that triggers the crash
3) meta information, e.g. which fuzzer etc. 

In addition to this you also get coverage reports based on LLVM coverage that tells you how much of the code is executed by the fuzzers.

The reports are simply made available on a website (https://oss-fuzz.com) so you can see them in the browser. 
Does this clarify the layout of the reports?

**Comment by DavidKorczynski** [comment]
Note: The above closing of the PR was a mistake so reopening.

**Comment by mrks** [comment]
Looks great and we are all in favor of this. @mweisgut will work on this once he submitted his thesis. Give it a couple of days, please.

**Comment by DavidKorczynski** [comment]
> Looks great and we are all in favor of this. @mweisgut will work on this once he submitted his thesis. Give it a couple of days, please.

Awesome! 

To clarify the next steps, from an OSS-Fuzz point of view, we need to:
- merge this PR in (namely get a fuzzer landed somewhere)
- get an email (or emails) that will be used for getting reports (described above in the initial message)

Following that it should be good to go

**Comment by DavidKorczynski** [comment]
Have you had more thoughts on this?

**Comment by mrks** [comment]
Sorry for not replying here. We are all in favor for it. @mweisgut will join our team on May 1st.

I'll mention @mweisgut here a couple of times more so that this is one of the first things that @mweisgut looks at. ;)

**Comment by DavidKorczynski** [comment]
Ah cool! Thanks for the update @mrks 

@mweisgut let me know when you are ready. The only thing we actually need as of this moment to get things up and running on OSS-Fuzz is an email we can use for the project maintainer to receive bug reports and all the other information provided by OSS-Fuzz.

**Comment by mweisgut** [comment]
Hi @DavidKorczynski,

sorry for the delay. You are welcome to use marcel.weisgut@hpi.de for the testing results such as error reports.

**Comment by mweisgut** [comment]
@DavidKorczynski I received the first reports yesterday night. Thank you for integrating sql-parser into OSS-Fuzz.

**Comment by mweisgut** [comment]
Hi @DavidKorczynski, could you please add @klauck's email klauck2@gmail.com to the list of the error report receivers?

**Comment by DavidKorczynski** [comment]
> Hi @DavidKorczynski, could you please add @klauck's email [klauck2@gmail.com](mailto:klauck2@gmail.com) to the list of the error report receivers?

Yep: https://github.com/google/oss-fuzz/pull/6080

**Comment by mweisgut** [comment]
> > Hi @DavidKorczynski, could you please add @klauck's email [klauck2@gmail.com](mailto:klauck2@gmail.com) to the list of the error report receivers?
> 
> Yep: [google/oss-fuzz#6080](https://github.com/google/oss-fuzz/pull/6080)

Thank you.

**Pull request closed without merging**
