### PR TITLE
Update Toolchain for ARM Macs and add macOS CI stage

### PR DESCRIPTION
**Pull request by dey4ss**
This PR updates the Makefile and the format script to support the different brew library path on ARM Macs. Furthermore, it adds a macOS stage to the CI pipeline.

### CODE REVIEW

**Comment by Bouncner** [comment]
Do you think it makes sense to add a osx worker to travis?

**Comment by dey4ss** [comment]
I think there's no reason not do do so. I'm gonna have a look at it.

**Comment by dey4ss** [comment]
@Bouncner after quite some fiddling around, I added a macOS stage. To successfully run the tests, I suppressed memory leak checks when the tests do not run on a Linux machine (valgrind is only available there). Notably, the new CI stage uses Apple's clang rather than the brew version because installing llvm took quite long (up to 10 minutes, whereas the other stages run about 1-2 min). To still have get an indight on the used compiler, I print the compiler version in the CI.

**Comment by Bouncner** [comment]
Awesome!

**Review by Bouncner — APPROVED** [review]
Awesome!

**Pull request merged**
