### PR TITLE
Fix: use correct format specifiers for int64

### PR DESCRIPTION
**Pull request by timzimmermann**
This PR fixes two compiler warnings regarding format specifiers (macOS / clang):

```c++
src/util/sqlhelper.cpp:14:52: warning:
      format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
    printf("%s%ld  \n", indent(numIndent).c_str(), val);
              ~~~                                  ^~~
              %lld
sql-parser/src/util/sqlhelper.cpp:29:50: warning:
      format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
    printf("%s%lu\n", indent(numIndent).c_str(), val);
              ~~~                                ^~~
              %llu

### CODE REVIEW

**Comment by torpedro** [comment]
Thanks :+1: 
I'm guessing this is a specific distribution/compiler issue.
This is not occurring on Ubuntu with g++ 6.3.0, clang 3.8 or clang 4.0.
It's not occurring on our Jenkins CI builds either.
So we'll need a different solution working on both platforms.

This is mentioning a MacOS vs. Ubuntu issue: https://stackoverflow.com/questions/14073877/printf-and-llu-vs-lu-on-os-x

**Comment by timzimmermann** [comment]
As suggested in the link you provided, is there any reason to use `printf` instead of `cout`?

**Comment by torpedro** [comment]
No particular reason, we can change the implementation to use `cout` instead.

**Comment by timzimmermann** [comment]
Okay cool, thanks for looking into it. I changed all `[f]printf` calls in `sqlhelper.cpp`.
I also got an error when compiling `example`, which I fixed as well.

**Comment by torpedro** [comment]
Looks good! Thanks!

**Pull request merged**
