### PR TITLE
Add BIGINT DataType

### PR DESCRIPTION
**Pull request by dey4ss**
While playing around with the [Public BI Benchmark](https://github.com/cwida/public_bi_benchmark), I noticed that many queries and schemas use `BIGINT` as a data type, which is an 8-byte integer (cf. [Postgres](https://www.postgresql.org/docs/14/datatype-numeric.html)). Thus, `BIGINT` is equivalent to [our `LONG` type](https://github.com/hyrise/hyrise/blob/377befb4a05d4b5c866f8c19b327b99f300aebf9/src/lib/all_type_variant.hpp#L37)  and can be implemented either as own type or as an alias that is parsed to `DataType::Long`. 

This PR adds `BIGINT` as an own `DataType` (subject to discussion). After this PR is merged, we can easily update Hyrise to handle `BIGINT` as `LONG` values.

### CODE REVIEW

**Comment by klauck** [comment]
Good catch.
Could you please add tests:

**Comment by dey4ss** [comment]
I'm gonna add corresponding tests in the next days. Do you prefer an own `DataType` for `BIGINT` or should we only add the token and parse it to `LONG`?

**Comment by klauck** [comment]
I would (leave it as it is) and add an own `DataType:BIGINT`.

**Review by klauck — APPROVED** [review]
Looks good to me.

**Comment by dey4ss** [comment]
Oh, just happened to me accidentially while merging: Don't we have squash commits as default?

**Pull request merged**
